In [41]:
import cv2
import numpy as np
import os.path
from tqdm import tqdm
from PIL import Image
from torchvision.transforms import ToTensor
import torch



In [43]:

img = cv2.imread('./darkness/Cars362_Z23wh0461.png')
print(img.shape)
# print(img)
b, g, r = cv2.split(img)
# cv2.imshow('g', g)
# cv2.imshow('b', b)
# cv2.imshow('r', r)
print(g)
cv2.waitKey(0)
cv2.destroyAllWindows()

(300, 400, 3)
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [165 117 122 ... 116 129 129]
 [180 168 174 ... 115 132 128]
 [190 193 194 ... 120 128 130]]


In [45]:
img_pt ='./darkness'
def load_images():
    img_path = './darkness/'
    imgs = []
    for file in tqdm(os.listdir(img_path)):
        imgs.append(np.array(Image.open(img_path + file)))
    # both input images are from 0-->255
    return imgs

images = load_images()
images = Image.open('./darkness/Cars362_Z23wh0461.png')
# print(images[0][2])

# rgb_im = images.convert('RGB')
i = np.array(images)
print(i.shape)

img = torch.as_tensor(np.array(images, copy=True))
img = img.view(images.size[1], images.size[0], len(images.getbands()))
# put it from HWC to CHW format
img = img.permute((2, 0, 1))
print(img[1])

# tf = ToTensor()
# new = tf(i) 
# print(new[1])
# cv2.imshow('i',i)
# cv2.waitKey()
# cv2.destroyAllWindows()


# r, g, b = rgb_im.getpixel()



100%|██████████| 2/2 [00:00<00:00, 457.32it/s]

(300, 400, 3)
tensor([[  0,   0,   0,  ...,   0,   0,   0],
        [  0,   0,   0,  ...,   0,   0,   0],
        [  0,   0,   0,  ...,   0,   0,   0],
        ...,
        [165, 117, 122,  ..., 116, 129, 129],
        [180, 168, 174,  ..., 115, 132, 128],
        [190, 193, 194,  ..., 120, 128, 130]], dtype=torch.uint8)
