In [2]:
import cv2
import numpy as np
import os.path
from tqdm import tqdm
from PIL import Image
from torchvision.transforms import ToTensor
import torch

/home/percv-d0/anaconda3/envs/yoloenv/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:

img = cv2.imread('./darkness/Cars362_Z23wh0461.png')
print(img.shape)
# print(img)
b, g, r = cv2.split(img)
# cv2.imshow('g', g)
# cv2.imshow('b', b)
# cv2.imshow('r', r)
print(g)
cv2.waitKey(0)
cv2.destroyAllWindows()

(300, 400, 3)
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [165 117 122 ... 116 129 129]
 [180 168 174 ... 115 132 128]
 [190 193 194 ... 120 128 130]]


In [31]:
img_pt ='./darkness'
def load_images():
    img_path = './darkness/'
    imgs = []
    for file in tqdm(os.listdir(img_path)):
        imgs.append(np.array(Image.open(img_path + file)))
    # both input images are from 0-->255
    return imgs

images = load_images()
images = Image.open('./darkness/Cars362_Z23wh0461.png')

# rgb_im = images.convert('RGB')
i = np.array(images)
# print(i.shape)
# print(i)

img = torch.as_tensor(np.array(images, copy=True))
img = img.view(images.size[1], images.size[0], len(images.getbands()))
# put it from HWC to CHW format
img = img.permute((2, 0, 1))
# print(img[1])
 
img_np = np.array(img)
cv2.imshow('origin', i) # the second param of imshow must be np.array
# cv2.imshow('B',img_np[0]) # Blue
# cv2.imshow('G',img_np[1]) # Green
# cv2.imshow('R',img_np[2]) # Red

merged = cv2.merge((img_np[0], img_np[1], img_np[2]))
cv2.imshow('well?', merged)
# print(img_np[0].shape)
cv2.waitKey()
cv2.destroyAllWindows()

# r, g, b = rgb_im.getpixel()

100%|██████████| 3/3 [00:00<00:00, 375.16it/s]


In [27]:
gr_img = np.mean(i, axis=-1)
print(gr_img) # grm image is 300x400
print(gr_img.shape)
print(gr_img[299])


[[  0.33333333   0.33333333   0.33333333 ...   0.33333333   0.33333333
    0.33333333]
 [  0.33333333   0.33333333   0.33333333 ...   0.33333333   0.33333333
    0.33333333]
 [  0.33333333   0.33333333   0.33333333 ...   0.33333333   0.33333333
    0.33333333]
 ...
 [172.33333333 128.33333333 132.         ... 113.33333333 127.33333333
  127.        ]
 [182.66666667 172.33333333 177.66666667 ... 112.33333333 129.66666667
  126.33333333]
 [188.66666667 192.66666667 192.33333333 ... 117.66666667 126.33333333
  127.66666667]]
(300, 400)
[188.66666667 192.66666667 192.33333333 191.33333333 192.66666667
 193.         189.         187.33333333 189.         192.33333333
 193.33333333 193.66666667 193.         193.66666667 192.66666667
 192.66666667 190.         190.33333333 190.33333333 192.66666667
 195.         194.33333333 191.66666667 189.66666667 192.66666667
 196.         196.         192.         191.66666667 192.66666667
 193.         196.         196.         196.33333333 191.66666667

In [36]:
wat = np.zeros_like(gr_img)
print(wat)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
